development:
  adapter: postgresql
  database: owl
  username: postgres
  password:
  pool: 5

test:
  adapter: postgresql
  database: owl
  pool: 5
  timeout: 5000
  username: yellowbkpk

production:
  adapter: postgresql
  database: owl
  pool: 5
  timeout: 5000
  username: yellowbkpk
